### PR TITLE
Better steam icon

### PR DESCRIPTION
**Pull request by luisrguerra**
The current steam icon is not recognizable, I made this one more similar to the original.
New icon:
steam

Current icon:
steam-old

### CODE REVIEW

**Comment by zeparu** [comment]
looks like this change has some issues

on KDE panels, the transparency is not rendered correctly

image

**Comment by luisrguerra** [comment]
> on KDE panels, the transparency is not rendered correctly

KDE has problems rendering SVG, probably having problem with clipping mask effect

**Comment by luisrguerra** [comment]
I tried to fix the problem, I don't have a KDE to test at the moment but it should work #33 
steam

**Comment by vinceliuice** [comment]
Fixed now

**Pull request merged**
